ROOMS = [
    "Shrine: Statue of a headless goblin.",
    "Caterpillars spinning cocoons beneficent and not.",
    "Burial pool.",
    "Slippery funnel leads down 4 levels.",
    "Shimmering drifts of powdered glass fill the corners.",
    "Heavily armed goblins without pants , tripping on mushrooms.",
    "Circular floor channel shifts things clockwise: 10 mph.",
    "Open sewer, mysterious gleaming. Possibly gems?",
    "Magical darkness. Thorny pits. Save vs. Wis.",
    "Ordinary fountain. Decoration of fawns and centaurs.",
    "Guard post for humanoids beyond. Trapped wall.",
    "Forest of rusty spikes. One undecayed: magical lance.",
    "A well surrounded by hallucinogenic fungus.",
    "Tree grows fruit made of candy, And pain.",
    "Grain silo, rotting. Giant rats, cockroaches, ergot demons.",
    "soft loamy ground, giant spiders kidnap anyone resting.",
    "Oubliette. Skeletal prisoners, signs of furious, futile scrabbling.",
    "Ventilation shaft; cold hearth below. Stars visible above.",
    "A pentagram of chalk and antlers spews ash.",
    "A salt dryad's boudoir. Con save or desiccate.",
    "Gnawing homunculi widen the corridor. Oblivious to sounds.",
    "Windchime of bones; magical repository for stolen secrets.",
    "Illusionary spike trap hides real trapdoor to pit.",
    "Giant crystal, mostly shattered. Recently.",
    "Store cupboard of orc uniforms.",
    "Stone faces on the walls breathe fire.",
    "Rotating stairwell wound up daily by ogres.",
    "Three treasure chests, one is a leathertarian mimic.",
    "Buried boat. Kingly skeleton. 6 sacrificed guardians.",
    "Room swaps brains, removes memories, till you leave.",
    "lush overgrown garden, where's the light coming from?",
    "Remains of a burned library.",
    "Sixteen skeletons on a dead man's chest.",
    "impaled demon masks. May possess wearers, grant powers.",
    "one man, cloaked in void, likes dogs &nbsp.",
    "large circular chair, big enough for lounging giant.",
    "Magical mirror shows past adventuring groups passing through.",
    "Dwarf skeleton lying intertwined with elf skeleton.",
    "Skeleton laments lost empire in song, seeks renewal.",
    "Myconids tend their young in this natural cave.",
    "Ossuary. Clay golems making instruments from the bones.",
    "Dumbwaiter and speaking tube.",
    "Meticulously empty. No mould, no dirt. Chlorine smell.",
    "Gelatinous pits: cubes mined from here.",
    "skeleton wearing empty backpack, is actually Mimic.",
    "The ceiling is covered in black cones.",
    "Water (impure) pours from small fissure in ceiling.",
    "secret gate into portable-hole-space.",
    "Injured mount monster, saddle still on.",
    "metal pipes, clanging rhythmically. Morse code? Birdsong?",
    "A hag's lair. Decorated like a nursery. Puppies.",
    "Morose lizardmen, craving leadership milk.",
    "Steps up to altar spattered with tongue parts.",
    "elegant dining room laid out for full meal.",
    "Bells ring, Sound seeks birth inside you.",
    "Storage room full of food. All is poisoned.",
    "barrels of hard liquor. Automaton guard.",
    "Well closed off by heavy iron bars.",
    "Two gardens: one orderly, one overgrown and fecund.",
    "Massive corroded brass organ overlooking Sunken Prison.",
    "Iron statues overgrown with poison ivy.",
    "too much light makes the baby go blind.",
    "Goblin border post. Ask to check your weapons.",
    "Family of four gnomes made their homestead here.",
    "Control panels, decayed. Iron rations in tins. Periscope.",
    "Half-empty weapons rack for energy lances, six left.",
    "Goblin patrol, using waxed human arms as torches.",
    "Possessed animal in office.",
    "Metal cupboard holds 28 bottles with random potions.",
    "Armory. Rusted weapons are functional. Pristine are cursed.",
    "Poorly-disguised storage pit contains hands of glory.",
    "walls curve around dance of sleeping walking encephalopathic trolls.",
    "Table with faithful miniature representation of dungeon level.",
    "A giant throne of fur and mammoth tusks.",
    "Dark, twisty, flickery, crystal corridors. Invisible thief.",
    "Two crates with water-proofed scroll holders.",
    "Iron foyer door forged from gun barrels.",
    "Ceremonial archway in center changes alignment.",
    "Time sink: every round here takes an hour.",
    "Names of the fallen inscribed on oaken panels.",
    "Severed animate head gives dungeon news.",
    "weapons of all eras embedded in caged troll.",
    "Large iron mirror steals soul when gazing in.",
    "Swarm of albino rats covers floor.",
    "Abused Henchman Soviet meeting.",
    "Hollow eggs contain random live miniature humanoids.",
    "Two arguing demons appear trapped under candle wax.",
    "Recurring enemy's secret hideout. Papers for aliases, plans.",
    "Three mosaic lunettes with names behind iron screen.",
    "Carved names appear on walls when adventurers die.",
    "checker board floor teleports randomly between tiles.",
    "Glow worms hang from ceiling. Skeletons cover floor.",
    "Mushrooms on all surfaces. Some beneficial, some dangerous.",
    "Vandalized portraits. Fixing them solves a problem.",
    "Broken dimensional gate. Repairable with parts from dungeon.",
    "Wild magic zone. Currently home to living spell.",
    "Cursed sword stuck in blessed stone.",
    "Pit-bound lobsterman uses portable hole as trap.",
    "Tomb of unknown soldier, sun lights on solstice.",
    "Human skull lies inside crumbling wall.",
    "Correspondence with distant lord, dropped.",
    "Storehouse covered in honey, ants.",
    "Sleeping NPC party. Guard passed out drunk.",
    "Lizardmen standing waist-deep in null-magic liquid.",
    "Bloody footprints lead to a blank wall.",
    "Deserted barracks. Very dirty.",
    "Ceiling drips mineral water.",
    "Bridge over drainage canal.",
    "Office for messenger-rats. Rat-man clerk.",
    "Magic mouth speaks totally alien language.",
    "Control room allows switching doors open/closed.",
    "Chamber of many eyes.",
    "Baptistry of flaying tongues.",
    "Discouraging smell reminds you of past failures, grudges.",
    "Decaying floor. Falling through leads to lower level.",
    "Amber roof casts natural, blinding sunlight.",
    "Echoing halls of pestilent memories.",
    "Brazier, unfinished meal, still hot.",
    "Well leads down three levels.",
    "Brackish water slowly fills room if sealed.",
    "Flammable stone. Once lit, never extinguished.",
    "Library, badly damaged.",
    "Library, intact, being browsed by dark creeper.",
    "Torture room with steam-powered implements.",
    "Crystal orb, too close to pit edge.",
    "Seven secret doors, all trapped, fake. No escape.",
    "Portal (1d6) Tanelorn, Cadwallon, Greyhawk, Sigil, Credia, Vornheim.",
    "Deserted forge. Half-finished glowing axe blade on anvil.",
    "Dead live in water pool. Children flayers.",
    "Ceiling replicates sky outdoors.",
    "Fear of possession resulted in this goblinoid abortion.",
    "Finally some fucking treasure, chests, guarded by elves.",
    "Floor like the sea. Save vs drowning.",
    "Chimerological laboratory with lots of parts. None alive.",
    "Scriptorium holds Book of Priests. They are skeletons.",
    "Wheel rearranges constellations on floor. Opens other areas.",
    "Really Useful Engine parts.",
    "Maze with invisible walls. Cheese wheel in center.",
    "Lamp oil, sentient.",
    "This room is ON FIRE because salamander.",
    "Purple river resurrects fallen. Sacrifice the youngest.",
    "green glowing rod submerged under hot spring.",
    "Once there were stairs here.",
    "A root of Yggdrasil bisects the room.",
    "Magical water shrinks you mouse-sized when drunk.",
    "Dungeon tavern. Various humanoids mingle. Not necessarily hostile.",
    "Chains and bells tinkle in putrid, moist darkness.",
    "Room filled with smoke. Hallucinations when inhaled.",
    "the Philosopher welcomes you to your new home.",
    "Adventurer or inhabitant corpse. Potion in pack.",
    "Reliquary holds remnant of dead god.",
    "Flagellants line the walls, whipping themselves.",
    "Copper rats, sacred to goblins: bestow authority.",
    "small wooden box, closed but not locked, rattling.",
    "Roof covered with giant vampire bats. Consider running!.",
    "Drawer in wall connects inexplicably to your backpack.",
    "Eye of Mazrabaan glitters high above choral citadel.",
    "the pool of water is on the ceiling.",
    "Several severed hands, all without middle finger.",
    "Philosopher's stone. Good for 20lb of lead.",
    "Crying stone baby creates gravity well, attracts missiles.",
    "Shield wall. This wall is made of shields.",
    "Plush velvet wingback chairs. Platinum hookah. Lamia.",
    "Magnet trap, carrion crawler, clustered dead.",
    "Deep pool of black water, skeletons on bottom.",
    "Empty.",
    "Who knows what Ulcer Priest hid in strongbox.",
    "Stacks of gnawed and cracked bones, like firewood.",
    "Walls have victims of mis-teleport half-stuck in them.",
    "Invisible wizard looking for an exit.",
    "Party's faces appear on statues. Unseen woman laments.",
    "Fully operational coin mint. Lacks base materials though.",
    "We ate them all - says elf and grins.",
    "Library of lost books. Research anything (1d100 days).",
    "Hound of Tindalos trapped inside flammable jelly cube.",
    "Mill of souls does not operate today.",
    "Fancy sarcophagus leaks blood, creates imps.",
    "Corridor of traps, all activated, sabotaged, save one.",
    "Like the room to the north plus worms.",
    "Gigantic metal snake eats thousands, absconds them elsewhere.",
    "Candles, coins on the floor, three locked doors.",
    "Dark, damp. Once inside wall fungi start glowing.",
    "Magic smithy. Golem stuck making minor trinkets.",
    "This dust makes you high. Ten foot high.",
    "Elaborate wrought iron cage contains naked witch.",
    "Mind flayer meditating in throne of dead elf.",
    "goblins around table, playing game with map, dice.",
    "Eight orcs ate orcs.",
    "Blue-furred gnolls play dice, armed with javelin-snakes.",
    "Lone warrior on top of pile of orks.",
    "Pool. Echoes.",
    "Sobbing head of child stuck on killing monster.",
    "Seven secret hands of doom.",
    "Rust monster torturing iron living statue.",
    "Iron golem needs cure for depression.",
    "Statue holds piece of rod of seven parts.",
    "Crypt. Bugs.",
    "Brass statue shoots lasers at paladins and clerics.",
    "Shroud spider lair. 1d8 paralyzed victims.",
    "Gate into half-scale copy of campaign world.",
    "Gravity pulls toward west wall. Displacer beast.",
    "Marble altar holds shriveled silver-nailed six-fingered han.",
    "Mountable monster stable, six stalls filled.",
    "Buried longship infested with immortal crab people.",
    "Subterranean arena. Fight for glory and grand prizes!.",
    "There are seven skeletons in this closet.",
    "No skeleton in this closet. Rats.",
    "Dust covered kitchen. D4 ghoul cooks.",
    "Extremely high ceiling, narrow spiral stairs eroded away.",
    "Four greyhounds eat raw meat off black tiles.",
    "Ghoul cooks are in fact cursed princesses.",
    "Glass sphere contains black pudding and green slime.",
    "Missing prince sleeps on pedestal. Impossible to wake.",
    "Sun chariot; horses and one wheel missing.",
    "Snow globe sucks you in when touched.",
    "Wode tattooed pigs pursue, nipping at heels.",
    "Floor collapses, revealing prizes of those before you.",
    "Fragmenting floor trap. Cursed diamond.",
    "Piercers everywhere.",
    "Quicksand floor, room entangled with tree roots.",
    "One hundred and sixty seven rods of manipulation.",
    "North wall strong magnet, attracts all metals.",
    "Cells, shadows, Spinneskelle.",
    "Fractal ooze suspended in glass cage.",
    "Cell holds guy in iron mask.",
    "Copper basins filled with hagfish, tended by monk.",
    "Gigantic mechanical computer/machine tells future, 50% right.",
    "Thirteen adult bodies sewn together in one giant masterpiece.",
    "Giant black heron worshipped by crucified witches.",
    "Empty.",
    "Dust covered remains of 1d6 humanoids.",
    "Giant lizardman hones his sword, sits on trapdoor.",
    "Northern wall is illusionary, hiding treasure.",
    "A vampire tends to her thralls here.",
    "Huge pile of stakes. Note says 'No hammer?'",
    "Ancient tapestries cover the walls and hide doors.",
    "Stone floor covered in lurid green grass.",
    "Goblins have stuffed the pigs with snake.",
    "An otyugh sits upon garbage, dispensing questionable wisdom.",
    "Black throne, inlaid with marble eyes. Night hag.",
    "Ice sculpture of large crane, egg embedded inside.",
    "A parlour. Couches, bookshelves, large pillows. Chrysanthemums.",
    "Entrance to the Underdark, through living giant worm.",
    "Luminescent ink fountain. Anything removed glows ten days.",
    "Cursed ape-skin whip deals damage to wielder.",
    "Passwalling thief pickpockets stuff. Flees east.",
    "Techno dwarfs calibrate huge drill for excavation.",
    "Discarded yeti prototypes.",
    "Museum of skin.",
    "Control room with levers and buttons and lights.",
    "A knight in green armor and his goat scorpion.",
    "Winch opens portcullis on a lower level.",
    "bridge over river, a place to rest.",
    "Six lions, lounging on luxurious pillows.",
    "Here lives a tiny dragon that zaps you.",
    "air elementals won't let anybody leave room.",
    "Unerring bow, with instructions. Requires unicorn gut string.",
    "Carved circle in floor disenchants items.",
    "Demonic altar summons blood-sucking flies.",
    "goblet, white liquid, snickering goblins.",
    "Stairs out. Leads to baron's cellar.",
    "Here waits +5 Vorpal Slayer Of All Knights.",
    "Color-coded ropes to bells in other rooms.",
    "Dead end. (Map says otherwise, may be illusion).",
    "Drunken wizard cheers the imps with grog.",
    "Grave with your name, obviously from ancient times.",
    "Basin of water holds sliver of the moon.",
    "Black crystal statue (valuable?) causes horrid hallucinations.",
    "Vials of uniquely brightly coloured dusts. Valuable pigments.",
    "Giant clockwork, controlling all time outside this room.",
    "Seventy-seven steep stairs descend into darkness.",
    "Pool of divine commune. Offerings necessary.",
    "Dragon egg on fire, carefully tended by kobolds.",
    "Ranting human attempts to stab any demi-human.",
    "Here light does not cast shadows.",
    "Gremlin heads hollowed to make various grenades.",
    "Two hobgoblins oil-wrestle. Many females cheer. Throw coppers.",
    "Small white rabbit. Turns out harmless.",
    "Wet clay walls, locals leave hand and head prints.",
    "Lots of ants, carrying body parts around.",
    "Four thieves transport huge cache, then explodes.",
    "Interrogation room. Feathers, love potions, alcohol, caged Goblin.",
    "Collection of crystal skulls harboring alien intellects.",
    "Bugbears ambush from chambered ceiling.",
    "Adventurer with eating curse, too fat to escape.",
    "Secret compartment in ceiling holds vomit and treasure.",
    "Walls depict horrible sacrifice. Humans eaten by monster.",
    "Sword in stone on throne of bone, groans.",
    "Bowl of drowning on watery altar.",
    "Journal of explorer, written in blood.",
    "Teleportation device to dungeon entrance.",
    "Stacks of ruined mouldering books on iron spikes.",
    "Moss covered north wall reveals many footholds.",
    "Bejewelled reliquary atop shaft of poisoned spikes.",
    "Halfling Knight of the Bottomless Pit eating pears.",
    "Water wells from center hole, streams up walls.",
    "Giant spiders trap and cocoon the unwary.",
    "Behind this doors, eight more await.",
    "Sediment fills this room to the ceiling.",
    "Access to sniper's gallery above 2d6 neighbouring rooms.",
    "Seven lost dwarfs, arguing.",
    "Halfling hooked to machine drools jale slime.",
    "Beholder holds court over blinded medusas.",
    "Bottles of poison gas atop rickety pillars: careful!.",
    "Fire breathing dragon atop treasure hoard.",
    "Beheadad elves branded with fae rune for 'boring'.",
    "Rube Goldberg machine makes healing potion, needs opals.",
    "Stone jars with pickled herring.",
    "Orc sleeping.",
    "Footprints, running.",
    "Room of mirrors. Each saves one memory.",
    "Ceiling hole leads to other times and places.",
    "Discarded length of chain attached to broken collar.",
    "This chamber is tidal.",
    "Doors of room distort echoes in nearby rooms.",
    "Slowly moving stone orrery. Tampering shakes dungeon.",
    "Lots of barrels, full of foul water.",
    "This room suffocates all in 1d4 rounds..",
    "&nbsp;overflowing with rotten food due to faulty Cornucopia.",
    "A fish tank.",
    "Friendly flesh golem provides possible henchman.",
    "Moat around perimeter, throne in center.",
    "Books about (1d4) history, magic, geography, local nobility.",
    "dagger - wounds trail blue ichor. Good for tracking.",
    "Injured mi-go, ready to bargain.",
    "Huge, sealed, stone jars filled with fresh blood.",
    "Blind minotaur walks mosaic labyrinth, holds lanter.",
    "Permanent dancing lights, dancing. To what?",
    "Flesh golem - damaged: needs new arms.",
    "Depowered mechanical bear. Find fuel, win companion.",
    "Stalactites and stalagmites close like teeth.",
    "A thief cries over corpse of dead companion.",
    "Inhabitant species' puppet theatre.",
    "Strange Cult sings praises for your prophecised return.",
    "Concert room with instruments. Playing one summons Olidammara.",
    "Four-armed gorilla enters your dreams if slain.",
    "sword in stone really a lever for pit-trap.",
    "It's bigger on the inside.",
    "pile of skulls, head of goblin scuplture.",
    "Spider web made from steel rope by dwarves.",
    "A dead tree covered in crawling claws.",
    "Valve wheel fills and empties a room elsewhere.",
    "Bottled vampire. Communicate magically or throw for rampage.",
    "Evil altar, offerings summon helpful imp.",
    "Quivering, gibbering slime walls shifting according to mood.",
    "large gem glued to floor. Much sniggering.",
    "Three magic mouths discuss philosophy.",
    "Wine barrels. Good vintage. One contains preserved monster.",
    "Ferns, mist.",
    "Giant stone nose sniffs passersby.",
    "Weeping child and Cockroach Demon.",
    "Green slime footprints end in apparent blank wall.",
    "Large brazier in floor, crated provisions, blankets.",
    "Empty. Smells less bad than elsewhere.",
    "Recent camp. Signs of battle. Deserted.",
    "Ancient mural of elves riding feathered tyrannosaurs.",
    "Some adventurers have hastily dropped their equipment here.",
    "Clockwork band plays national anthem, then attacks foreigners.",
    "Cobwebs and firewood.",
    "Wax museum curated by giant bees.",
    "Privy, finally.",
    "Dead dwarf under makeshift cairn. Wall partly excavated.",
    "Crystal ooze, escaped from nearby privy.",
    "Kobolds burning hobbit effigy.",
    "Hyena-man with halfling embedded in back eats pie.",
    "Sad donkey bears bags of plunder. Owners dead.",
    "broken bottles, discarded underwear, food, balloons.",
    "Bishop of the Demon Pope unpacking his valis.",
    "Tiny bronze shoes. Home to evasive hermit crabs.",
    "Giant lice (half inch long), love plate armour.",
    "Thick fug. Rancid divan. Sleeping Tallowbride.",
    "Stranded Githyanki spy cell: undead rations, khopeshes.",
    "Armoury. Twenty-seven different flails.",
    "Flying glass fish contain colored potions.",
    "Room gone. Black pit miles deep.",
    "Single mimic masquerading as altar, sacrifice, beastman priest.",
    "Brass reliquary, giant's toe, +3 strength if underfoot.",
    "Hobgoblin school of fence. Six visiting masters.",
    "Reversed gravity. Collapsed ceiling leads to upper level.",
    "Blood cellar, vampire blood tasting ongoing.",
    "empty pit, bottom filled with tiny fish bones.",
    "Flooded room. Peeing kid statue(fountain). Someone who drowned.",
    "Dead ape god. He who would be king.",
    "Loam.",
    "Prison cell, grey old woman inside, wants beer.",
    "Mole infestation. Next d6 rooms are spongy, weakened.",
    "Planeshifters made portal, start invading dungeon from here.",
    "Gothic two level room with battlements and courtyard.",
    "Tapestries depicting the last and next two rooms.",
    "Cloakroom, a living shadow hunts here.",
    "Insect egg hatchery. Piles of stripped humanoid bones.",
    "Lit with eternally-aflame bodies.",
    "Old humanoids are left to die here.",
    "Trap room (1D8+3 traps).",
    "Cakes. If eaten save or eat another (cumulative -1).",
    "Kennel, 2d10 dire dogs, body parts.",
    "Shrine: statue of woman rising out of mushrooms.",
    "Empty bunk bed.",
    "Shrine: handsome statue has face on both sides.",
    "Oil, 5' deep.",
    "Moving room (like the staircases in harry potter).",
    "Everything you say here is heard by angels.",
    "Reverse gravity.",
    "Fearsome standing wolf statue surrounded by votive candles.",
    "The lich's moving men, laden with furniture, organ.",
    "A hog house.",
    "Spun-glass statue, cradled by sleeping ettin.",
    "Subtle door found if 3 light sources present.",
    "Shrine: statue of vulture-headed man draped in robes.",
    "Reverse intentions. Save or do the opposite.",
    "Statue alcove, empty. Garden, trampled. Letter, discarded.",
    "The dragon's nest with egg. 50% dragon here.",
    "Temple, missing altarpiece. Dead abbot tattooed with map.",
    "Seems like river Styx goes through here.",
    "Roots of the Demon Tree, remains of victims.",
    "Smashed furniture.",
    "Woman in red dress weeps on golden throne.",
    "Vase with violets, red cake. Sign: 'Eat me.'",
    "Air elemental asks for help, trapped whirlwind.",
    "Dead former henchmen lie in ambush.",
    "alien writing on walls. pictures of disgusting creatures.",
    "Snake statue of green metal, gem in mouth.",
    "Bottle of every emotion. Somebody drank hate.",
    "Goblin Queen copper bust. Rubbing nose brings luck.",
    "Kobolds lair in the celling, with boiling oil.",
    "Dungeon crabs, fencing.",
    "Kobold nobles, having tea. Precious furniture.",
    "This is the bottom of the bottomless pit.",
    "Inhabitant's living room.",
    "Weapon storage. One magic rusty dagger left.",
    "Workshop of a mason.",
    "Workshop of a gem-cutter.",
    "Workshop of a sculptor.",
    "Wood storage. Mostly soaked and rotten.",
    "Acid drips from ceiling. Somebody installed bottling plant.",
    "Here lies the oblong rug.",
    "Giant chained to anvil, forced to forge weapons.",
    "cold furnace with piles of books around it.",
    "Former throne room, now an abandoned storage room.",
    "Prison cells (1d4) POW, human flock, thief, murderer.",
    "Rough furniture, singing bird in cage.",
    "Mud pit full of eels.",
    "Bedroom.",
    "Cartographer's room.",
    "Living room, furniture made of rat bones.",
    "Deformed skull with magic mouth spell welcomes visitors.",
    "Dozens of 10' poles: splintered, cracked and broken.",
    "Frogmen gamble over bone dice. Biggest one cheating.",
    "Doormaker's workshop. One magical door leads home.",
    "Tesla coils, iron cage, hanging chains, sleeping abomination.",
    "Engineer's workshop, 1d4 automaton guards.",
    "frog statue, insects placed in mouth become gold.",
    "Goblins fighting over mushrooms.",
    "Dismembered cow.",
    "Built of the bones of the sacrificed god.",
    "Knee-deep in dead gelatinous cube.",
    "Sealed insulated storage vats of liquid nitrogen.",
    "Empty",
    "Yuan-ti, spread open and staked to wall. Knows secrets.",
    "Dimension-hopping merchant, not interested in gold.",
    "Glass columns, each filled with gas (cloudkill, sentient)",
    "Bisected by river of molten brass golem blood",
    "A cage of rusty bars, reeks of spices.",
    "Summoning circle, brimstone smell, dead wizard.",
    "dense with fragrant flowers, blossoming from hidden corpses",
    "Floor strewn with multicoloured shards of broken glass.",
    "Buboe goblins, in agony,  scraping sores with potsherds",
    "Illusionary bottomless pit.",
    "Wall stones revolve in place, loud, grit abounds",
    "Floor to ceiling, wall to wall: Owls. Pressurized.",
    "One wall open, clouds huddle below. Birds roost.",
    "A little girl.",
    "Iron medusa devouring pillars of petrified victims",
    "Two children with black fingers devour third",
    "Trap-making workshop. Spikes, chains, hinges, levers, acid.",
    "Grease fountain. Statues resemble party members.",
    "Total darkness; the sensation of moving through slime. ",
    "Eight swords, seven cursed. Sad guardian wants moon.",
    "Razorvine garden overlooking torture chamber. Beautiful attendant-amputees.",
    "Crushing outward pressure, blinding light, and Radiance Demons.",
    "Stone dwarf caryatids need you to replace them.",
    "A clapperless bell, sleeping beauty with secret tail.",
    "Altar with woman in glass sarcophagus.",
    "Room hip-deep in teeth. No fairy.",
    "Several Surly Magic Mouths. Warning: Do Not Feed.",
    "Bad air snuffs flame. Hard to breathe.",
    "corpses smushed into floor,  intestines cling to ceiling.",
    "Wide-eyed vestal conceals bloody knife, children&#39;s fingers",
    "Hundreds of stone statues. Basilisk. Blind assassin.",
    "Alchemy laboratory, recently used, candles still burning.",
    "Beatific Font of False Prophecy. Guarded by Serpents.",
    "Elderly naked people daubed in gore, laughing maniacally",
    "A headless dragon towers upright, succubi under talons",
    "Altar of plenty requiring the sacrifice of Christians",
    "Naphtha sump. Fumes highly flammable and poisonous.",
    "Only a closet, filled with tiny biting ants.",
    "Stone dragon head, throne of sleeping demon prince",
    "Pheasant in cage hastily dropped...by something.",
    "Weeping figures of ash. carpet of beetles.",
    "Scattered furniture. 400 gp hidden in couch",
    "Earthen pots with plants that have spellcasting eyes.",
    "Tube worms pulse like a red carpet.",
    "Smelly dwarf cooking something smelly in a cauldron.",
    "Giant&#39;s testicles, still warm and an etch-a-sketch",
    "A jumble of bones inset with gold.",
    "Hugely fat goddess, drunk, playing/sculpting flesh pillars",
    "A narrow pit, inside a friendly orc",
    "Empty, pre-activated pit trap.",
    "A well made bench; a dog sleeps underneath.",
    "walls of gold, will scream if touched",
    "Sleeping place with 8 mats.",
    "Scattered crumbs from meal of closest monster.",
    "Windowless, dark, smells of rotting leaves and corpses",
    "Duplicate of last room.",
    "Duplicate of last room.",
    "Lit by a single torch of brittle, black wood",
    "Xorn--considers this area of the dungeon hers.",
    "Mirror of last room. If damaged, both shatter.",
    "Mirror here reveals last room cavity rotting flesh",
    "Chains hanging from ceiling. Skeleton on a hook.",
    "Cells containing injured victims of nearby intelligent monster.",
    "Everything in other room audible here &amp; visa-versa",
    "The floor is lava, spanned by bridge.",
    "Illithids playing chess with sentient mice as pieces",
    "Armory. 1d6 weapons still useful, others rusted.",
    "Princess, trying to rescue prince from dragon",
    "Chasm with invisible bridge.",
    "Prince and goblin king, tripping on wyvern venom",
    "Chasm with sign &quot;leap of faith&quot;",
    "Goblin in pit trap, gives directions if rescued.",
    "inert Heavy Spectre capable of achieving superhuman density",
    "Sculptures of Non-Euclidean Gonads, discharge brings dark visions.",
    "Purple worm, contains living room, bored housewife",
    "Chimp in wedding-dress. Masturbates Furiously. Ejaculates Color Spray.",
    "Disabled sunseed, being sought by starborn valkyrie ",
    "A riding horse. Falls apart outside dungeon.",
    "Speaking stone statue. Answers questions. All lies.",
    "Illusion of broken bridge. Actually fine to cross.",
    "Mess hall. Soup still hot and steaming.",
    "Pieces of children&#39;s toys that reassemble and crawl.",
    "Round water hole in floor, excellent fishing spot.",
    "Blocking wall of ice. Melting releases frozen monsters.",
    "Hydra, harmonizing. Invisible sound wizard master.",
    "Post-traumatic paladin, kingdom wished away, strange reliefs.",
    "ice block sat in flames. Swordswoman lounges atop.",
    "Ancient tree. 1d4 strange fruits heal all hp.",
    "Small,  brittle structures, long abandoned",
    "Sound wizard&#39;s ear horn collection. Some magical.",
    "Telekenetic zombies cause maelstrom of rubbish and parts",
    "Empty Room: Mysterious sourceless screams sometimes speak secrets.",
    "Displayed: silver ball; dagger; flask. Cryptic warning. Harmless.",
    "Undead dwarven blacksmith, will happily repair weapons/armor.",
    "Bleeding walls: If healed/wrapped. Will help PCs.",
    "Much colder, clammy. Miasmas. Vent to lightless lake. ",
    "Sad orcish girl has become lost, violent family.",
    "Witch selling secrets for the names of children",
    "Kobolds, murderholes, crossbows, boiling oil. You know the drill...",
    "Chest: Map of another dungeon, hidden under false-bottom.",
    "Derro bachelor party/rumsprinnga. Trading mutations for booze.",
    "Floor is pool with acidic water weird.",
    "Wyvern babies. Hungry and lonely.",
    "Safe room. Glowing orb. Monsters will not enter. ",
    "Floor is dungeon&#39;s heart.  electricity pulses with beat.",
    "Kettledrum. Each beat will awaken one clay golem.",
    "Donut with doors opposite. Everything changes after passed.",
    "Amber statues of hunting animals. huge horn.",
    "Arena. All damage illusionary, restored when leaving ring.",
    "Four-poster bed. Touching sheets activates sleep spell.",
    "The first frog.  The last swamp.",
    "Time paradox continually respawns goblin until halted.",
    "Gold on the ceiling.",
    "Open graves. Crazy graffiti on doors. Magnetic tombstones.",
    "A ghoul-hating ghoul that doesn&#39;t know he&#39;s a ghoul.",
    "An exit.  Not THE exit.",
    "Railgun for the soul.  Karmic accelerators.  XP ammunition.",
    "The opposite of a panda bear.",
    "Two goblins fighting over a &quot;wife&quot;.",
    "Hole in the ceiling.  Bloodstains beneath it.",
    "The room is a centrifuge.  Killer orbs.",
    "Lurker and trapper mating.",
    "Lobotomized grell, dragging itself along pathetically.",
    "War machine from another world.  Ignores PCs.",
    "Ejected buzzsaws.  Broken trap.  Thief, now in giblets.",
    "19 zombies perpetually headbutting floor.  Mostly oblivious.",
    "Aggressive door approaches you.  Desires to be opened.",
    "Snakes?  No, chains.",
    "Skeletons siphon fat, growing stronger.",
    "A storm drain.  Music, discordant yet beautiful.",
    "A monstrous playwright.  A wardrobe.  An audience.",
    "A convocation of the rat tribes.",
    "Empty room.  Broken chair.  Hungry dust.",
    "Wendigo-ified berserker.  No feet.  Leaves bloody footprints.  ",
    "Outlined on the wall in ash, a family.",
    "A flumph, afflicted by a spinning sickness.",
    "A familiar--crocodile--cares for it&#39;s deceased witch.",
    "A hyena-lich.",
    "Pots and pans, as if to catch rain.",
    "Brass face.  Smell of vinegar.",
    "The giant&#39;s bellybutton.",
    "A priceless painting.  Thought stolen.  Now worthless.",
    "Lights and voices that flee from your approach.",
    "Tired bones, aching for burial.",
    "A bard.  His entourage.  Foolish, numerous, and amiss.",
    "Drow assassin, dying from  betrayal.  Lacking a shadow.",
    "Fog leaks from PC&#39;s orifices.  They are evaporating.",
    "Like a butterfly collection, but not of butterflies.",
    "Fungal-furnished pubroom for Underdark fun-seekers. Try the pies.",
    "Three fairies want song contest judged. Stakes: Life.",
    "Undergoing repairs. Piles of masonry and tools.",
    "Prisoner will trade ledger for glimpse of sunlight.",
    "Two driders argue over web-bound dwarf.",
    "Miniature forest with tiny animals, hags; lifesize frogs",
    "Barbarian with an arquebus. Many targets, none hit.",
    "Trompe l&#39;oeil paintings on floor of pit traps.",
    "Chains hang, 30&#39; ceiling; undead apes in shadows.",
    "Air full of sweet smell of honeysuckle, safety.",
    "Each step forward: migraine; each step back: euphoria.",
    "Drapery on walls hide hunting trophy ivory bones.",
    "Sendakian wild rumpus - owlbears, bugbears, feral human child",
    "Trap! Long slide to giant razor blade death",
    "Goblins reading party&#39;s races dirty joke book - laughing",
    "Piercers above, ropers below open hallway opposite",
    "Injured Knight of the Black Scorpion, seeking something.",
    "Nice rug, it really ties the room together.",
    "Four hobgoblins torturing a stirge they wounded",
    "Locked lead casket contains poisonous fallen star.",
    "Heap of stinking mud, filled with large eggs.",
    "Map of local dungeon, drawn in fresh blood.",
    "Tapestry depicts party members murdering one another horribly.",
    "A soiled apron and an over turned butterchurn.",
    "Brimstone golem and well of quicksilver.",
    "Ogre chained to a locked iron bound coffin.",
    "A vampire child attends an imaginary tea party.",
    "Erasmus, wereskunk in human form. Knows treasure location.",
    "Ogre zombie filled with ghouls.",
    "Map of dungeon in tiles on the floor.",
    "Cesspit.",
    "Captive rival dungeon party stripped to their undergarments ",
    "Dead wizard. Magic quill scribes biography on walls.",
    "Crystal spider statue surrounded by stinking blood trench.",
    "Dungeon Tavern. 1d4 random encounters enjoying nonviolent drinks.",
    "Animated knitting needles. 2d4 pairs. Many warm scarves.",
    "Disused adventurers&#39; campsite. Rations, bedrolls, circle of protection.",
    "Shimmering chrysalis. Humanoid husks. Cracked breast plates. Treasure!",
    "Detailed chalk drawings of four plausible futures.",
    "Decadent gothic ballroom.",
    "Giant animated marshmallow construct. Celebrating faeries. Newcomers welcome.",
    "Fresh corpse sitting upright staring at a corner",
    "Seven empty whiskey bottles. Seven long dead dwarves.",
    "Walls are made of unblinking eyes.",
    "Talking bear. Magic trinkets braided into his fur.",
    "Eight-armed statue of a forgotten god.",
    "Pool of clear water. Tiny humans bathing.",
    "Illusionary elf-maid. Quicksand pit. Intellect Devourer in hiding. ",
    "Hollow terracotta statue full of bees.",
    "Naked elven slaves chained to a sleeping giant.",
    "Floor covered in yellow and white rose petals",
    "Stone mouth in floor asks to be fed.",
    "Sourceless whisper saying &quot;Go ahead . . . do it!&quot;",
    "Three murals of ancient female astronauts being devoured",
    "Stench of burnt hair, angel armoured in bone.",
    "Paper snowflakes that tumble after you. Scissor golem.",
    "Eight different books concerning the Law of Octaves",
    "Large blue crystal dodecahedron, contains fetal planet eater.",
    "Loose brick reveals, packet of sordid love letters.",
    "Poison-trapped chest opens to spring pit trap.",
    "Abandoned golem lab. Restoration possible, with sufficient investment.",
    "Many birdcages, no birds",
    "Harmonize with music box to see secret door",
    "Spider&#39;s nest, hundreds of eggs, about to hatch.",
    "Wizard recharges magical rings in power well.",
    "Scriptorium where demonic monks write down flawed contracts.",
    "Invisible Stalker hiding in fountain on west wall.",
    "Empty.",
    "Foundry to make living statues, operated by dogmen.",
    "Insane dwarf runs underground trade post with success.",
    "NPC party at rest, alert, has trapped doors.",
    "Makeshift chapel to dark deity, choir practicing.",
    "A man infested by bugs, he loves them.",
    "Goblins fighting ogre for remains of elven noble.",
    "Cave troll crashes through north wall, wields hammers.",
    "Magic mirror lies to men, not women",
    "Iron-shod doors lock away seventeen dangerous criminals.",
    "Belligerent halfling is actually just a midget",
    "Elf trapped in paralyzed amber jelly.",
    "Footsteps in dust lead towards you",
    "Dwarven miners start digging operation to lower levels.",
    "Alabaster bust rotates without affecting room&#39;s eight doors.",
    "Intricate architecture like British houses of parliament",
    "Man-scorpion throws sacks of scorpions from gallery.",
    "Lich&#39;s contemplation chamber. 50% chance to encounter.",
    "Magic mouth presents riddles in impenetrable accent",
    "Desecrated crypt home to 1d5 wights.",
    "Boneyard is home to demented necromancer.",
    "Jackalwere and werewolf, friendly rivals, playing chess.",
    "Skeleton of ancient hero trapped to kill looters.",
    "Goblins on stilts wade through poisoned water.",
    "Trap control room. Pressing buttons resets traps randomly.",
    "Unconscious maiden is ruthless warrior.",
    "Bucket of bedbugs (and one goldbug) above door.",
    "Halflings tend shadowleaf field here.",
    "Ornery gnomish merchants, recently robbed. Rewards offered. ",
    "8 grey aliens operating on goblin, extracting brain.",
    "Half a bird near door, otherwise empty",
    "Gigantic aquarium, drained long ago.",
    "Otherworldly wizard locked in telepathic combat with mindflayer.",
    "Frogmen eating human legs.",
    "Iron coffins stacked like cordwood. Six contain ghasts.",
    "Frogs crawling on ceiling and walls.",
    "A bleating goat with sacrificial dagger in belly.",
    "42 stone blocks in pile.",
    "Reliquary with booby trapped holy hand grenade.",
    "An undead gelatinous cube bound.",
    "Three trolls eating each other",
    "northern part of floor illusionary, covers snake pit.",
    "Mouldering stolen paintings of the belle epoque",
    "snake pit.",
    "A salamander with a clockwork foot",
    "Vats of spare parts for bodies",
    "Giant snake that swallowed a live orc.",
    "Autodoc that malfunctions and creates crab people",
    "Ghostly sounds of Van Halen issue from cracks.",
    "Dead orc with spilled oranges",
    "Pile of watermelons conceals jack o lantern.",
    "Mirrored walls cause confusion and disorientation.",
    "glass roof allows spectators from upper level.",
    "ruined control room inhabited by intelligent ball lightning.",
    "Wizard&#39;s sanctum. Permanent light and silence spells.",
    "anti magic column absorbs magical energies.",
    "Big kitchen, pig on spit. Or a human?",
    "Gnome tinker tends to mechanical warthog.",
    "Makeshift camp of migrating myconids. Moldy.",
    "bear traps all over the floor.",
    "Empty.",
    "mind wiped humans serve party of illithids.",
    "Wine cellar. Orcs putting bodies into casks, surprised.",
    "Barrels of salted Halfling meat. Chewy hairy toe.",
    "Chess set with trapped squares that destroy playing pieces.",
    "Sign says &#39;Way out&#39;, points to hanging noose.",
    "Doomsday device - deactivated.",
    "Beehive full of hallucinatory fungus honey, insane bees.",
    "Skeleton-powered grist mill. Needs bones for giant bread.",
    "Mushroom beds tended by strange pale aggressive bees.",
    "Monkey-stamped crates of unprocessed narcotic subterranean flora.",
    "Weapons rack, pole arm is a trap lever.",
    "Walls, floor and ceiling are metal. No gravity.",
    "Room of cheese.",
    "Room full of mice.",
    "Twelve zombies - one a noble, still wearing ring",
    "Intelligent ooze develops crush on most charismatic PC",
    "Drow haggle with Illithids over svirfneblin slaves.",
    "Serene pool. Nesting place of brain worm larvae.",
    "Wicker nests hold cocoons, moaning sounds pleasurable",
    "Electric summoner&#39;s circle contains wraith.",
    "Floor a fungi shelf. Nests in above shelf",
    "Robot and children search for lost mothers",
    "Intellect devourer slumped in depression",
    "Fountain with boiling water. Stacks of clean linen.",
    "Medusa in labor guarded by stone golems.",
    "Eleven singing birds, each heard alone affects uniquely",
    "Mad wizard&#39;s kitchen, apparently he eats books",
    "Statue repeats lies spoken in its presence",
    "Chapel to disgraced Saint, defaced by angry worshippers",
    "Magic mouth answers honestly - audible everywhere but here",
    "Mindflayer on deathbed - lucid, talkative, serene; occasionally alone",
    "Wicker adventurer puppets, manned by goblins, bomb trap",
    "Storage room with cannon balls and blackpowder",
    "Ravens eating adventurers. Ravens know what adventurers knew.",
    "Cagey adventurers eating suspect meats",
    "Teen necromancer has fled village, begs for food",
    "Naked cowering escaped prisoner might be a doppleganger.",
    "Miniature men do meticulous military drill.",
    "Opera singer screaming, but you only hear music.",
    "Walls covered in writing. Spreads if touched.",
    "Merchant strung out on cough syrup",
    "Thieves guild refining formian polyps into drug",
    "Library. Some sections extend beyond physical plane.",
    "A bunch of dwarven engineers rebuilds west wall.",
    "Secret door relocates randomly, leads to same place",
    "Dungeon room in progress, scattered tools, unfinished trap",
    "Excavation site. Explorer, two aides, six workers.",
    "Half-mummified corpse. Animates if completed - roll reaction.",
    "Immortal eviscerated fairy bound in brass cackling.",
    "Little bunk beds, chew toys, kobold droppings",
    "On walls: apologies to party in own handwriting.",
    "Blood smeared walls. Otherwise, empty.",
    "Glowing, melon-sized orbs hover, copiously crying sweet tears.",
    "Shards of glass spin in midair until swatted.",
    "An old man sits on a chair, waiting.",
    "Puddles on floor leak up to the ceiling.",
    "Tsochar face-hugger parasite eggs everywhere; Mother guarding... ",
    "Huge pile of gold coins!  They&#39;re melted together.",
    "Plain, bare room.  Everything spoken comes out backwards.",
    "Eight marbles.",
    "Half-a-dozen hallucinating halflings tied to bedsteads.",
    "Operations table with coathangers instead of scalpels.",
    "Circular hole in east wall, 4 feet diameter. ",
    "Fanatical elves on goblin hunt.",
    "Scriptorium: parchment, quills, ink, desks. Nothing of value.",
    "Distillation apparatus made from glass (valuable, fragile).",
    "Cats barking at single cat with diamonds inside.",
    "Puffer-fish-man sleeping; will puff and prickle if woken.",
    "Treasure chest seems mimic, isn&#39;t; gold coins are.",
    "empty except poster; &#39;Exciting development oportunity, contact Barry&#39;",
    "king sized bed, obese woman overflows, looks terrified",
    "room is pitch black, light swallowed up greedily.",
    "demo-Buddha shrine, lit by haunted glow-globe",
    "valuable but obscene tapestries conceal bronze-equipped skeletons",
    "bachelor pad of the recently divorced bugbear",
    "doorway of forgetfulness, you entered for some reason.",
    "worn sign; remaining letters d,o,n,t,e,t,e,r. Inside hungry policeman.",
    " barrel of fun, 1 d100 goblins pour out.",
    "Invisible, anti-grav silver blades form werewolf prison. ",
    "Magnifcent door marks the Rakshasa&#39;s area of influence",
    "Disgustingly bespattered. Ceiling shaft holds Dire Corby roost. ",
    "Two wells. One&#39;s defended by driders, one isn&#39;t.",
    "Enormous chandelier hangs; each crystal a lost soul.",
    "Pantry. Valuable cheeses and wines plus human hams.",
    "Three Giant Pelican statues come slowly to life.",
    "Small labyrinth, piles of parchments stacked to ceiling.",
    "Ordure pit opens from the ceiling: stench unbearable.",
    "Yellowhag, Whitehag, Blackhag, threefold entity enacting alchemical pageantry.",
    "Irresistible maelstrom of howling madness centered on gnome.",
    "Particoloured Obstracklous Mammyjag extends pseudopod (as Ochre Jelly)",
    "Large cake, out jumps 3 harpies, cake spoilt.",
    "Acid-pool trap set by nearest intelligent inhabitant.",
    "Seven <i>turned</i> ghouls fleeing battle-nuns.",
    "Glowing Two-dimensional warrior-priests from the positive-negative material plane.",
    "Forest of candles in landscape of wax burying skeleton troupe.",
    "10 years of candlewax. Single candle. Something underneath.",
    "Faint disembodied laughter of children long dead.",
    "Zombie with golden crown sits on ruined throne.",
    "Walls blackened from recent fireball. Empty otherwise.",
    "Floating wizard staff. Take it, become wizard.",
    "Holy symbol, man high, painted on all doors.",
    "Unfinished summoner&#39;s circle. Instructions to complete on parchment.",
    "Cooling chest filled with ice cream. Horrible flavors.",
    "Cobbler&#39;s workshop run by gnome. Shoes exceptionally nice.",
    "Two racks of champagne bottles. Mediocre quality.",
    "Swordmaster&#39;s journal  (1000 XP to fighter while in possession).",
    "Black lotus in shadows. Releases spores when illuminated.",
    "Smokeleaf growing operation under continual light. Thoroughly trapped.",
    "Reeks of brimstone. Home to fire elemental.",
    "Bath house run by homesick halflings.",
    "Fountain produces hot water, heated by lava below.",
    "Finally, the exit to the dungeon. Guarded lightly.",
    "Stairs seem to lead up, but lead down.",
    "Someone left behind a rope ladder.",
    "Quicksand!",
    "Empty again? (No, invisible stalker&#39;s lair!)",
    "Goblins defecating on lost reliquary of sun deity.",
    "Empty altar awaiting victims; stained glass windows black.",
    "Invisible petrified halfling cultists of Kali",
    "Three chests of semiprecious stones and a mimic.",
    "A sheep chewing humanoid jerky.",
    "A loom, a cord, a pair of scissors.",
    "Bloody clumps of hair cover a silver statue.",
    "Translucent kuo-toa fish-humanoid mystic. Currently seeing watery visions.",
    "Masochistic tiefling strung up, chains to four walls.",
    "Fungus farm, undead farmers. Zombies shuffling, mushroom studded.",
    "Deep halflings fishing like bears. Will share.",
    "Paladin and succubi in stasis. Sweet gear. Dead?",
    "Paladin and Succubus in bed! Oh dear! Dead?",
    "Two ettins, devouring each other. A princeling cowers.",
    "Troglodytes beauty. Hints  at longing for fame aboveground.",
    "Texts about the alteration of lizardmen hormone messages.",
    "Hallway with windows, showing party&#39;s dreams and nightmares.",
    "Cistern of psychoactive jelly. Upon touch,  speak Chaotic.",
    "Giant golem components. Mephits nesting in chest cavity.",
    "A green lantern and a pair of red briefs.",
    "Apple tree tended by minotaur.",
    "Map of campaign continent. Major cities marked destroyed.",
    "Ogre Laird and Hagwife, expecting performers, applaud drunkenly.",
    "Longship burial. Eerie harping, wraith concubines, spectral chieftain.",
    "Terithran cooks for nearby masters. Will purchase ingredients.",
    "Ornate choak-pear in forgotten satchel.",
    "Starlit fields of Elphame. Every square a mile.",
    "Pusillanimous poltroon, having betrayed companions, seeks party membership.",
    "Murder-holes, tripwires, gas nozzles, pressure plates, not trapped",
    "Floating giant heart, beating above stained marble tile.",
    "3000 drawers. One contains dungeon boss&#39;s greatest fear",
    "Copper sword in stone mould grants svirfneblin monarchy.",
    "Kobolds playing indoor soccer with a halfling head.",
    "Dwerger storeroom, tin ingots, diagram showing nearby traps.",
    "Several empty animal cages with doors ripped off",
    "Discarded baselard with broken blade. Vague fishy smell.",
    "&quot;War is Over!&quot; emblazoned on wall.",
    "Secret tomb of peasant revolutionary. Fresh offerings.",
    "Corpse in crypt not Withered King, despite tombstone.",
    "4 champions of chaos, preparing for war",
    "A female hobgoblin giving birth. Two goblins attending. ",
    "Icicles &amp; frost form on adventurers&#39; lips, chins, cheeks. ",
    "Dancing blade sharpens itself on grinding stone, hungrily.... ",
    "Hobnail. Pound into goblin&#39;s head to produce hobgoblin. ",
    "Walls absorb and echo all sounds continuously forever. ",
    "Silence kills sound 1&#39;  from source. Ears bleed.",
    "Alchemical charts litter the room, some useful.",
    "Statue of satyr urinates quality alcohol.  Weak stream.",
    "On opening the door, completely filled with marbles.",
    "Helium fills the room, everyone sounds like chipmunks",
    "what happens if you read a scroll in chipmunk?",
    "Gigantic Turtle and Slug locked in mortal combat.",
    "Rune that paralyzes with a staggering, true revelation.",
    "Hole in ceiling, rope dangles invitingly, pulled up!",
    "Scattered remains of statue, put together is PC.",
    "Large snake is random wormhole to another room.",
    "Giant penis statue covered in healing fungus.",
    "Shrine to Dolorous Queen, weep and be healed.",
    "Battle Princess wrestling six-armed abomination for silver treasure.",
    "&quot;They&#39;re everywhere&quot; written on wall. Another Invisible Stalker.",
    "Elf weeps over broken sword, tells of treasure.",
    "Ogre twins sitting down to dinner; human soup",
    "Redneck brothers with shotguns, lost in time.",
    "Fountain provides highly mutagenic &quot;water&quot;.",
    "Delicate flowers; fluorescent pollen persists on skin, clothing.",
    "Lobotomized dwarves burrow mindlessly, breaking down south wall.",
    "A sulphurous smell betrays the fire imp hiding here.",
    "Broken chains hint at gigantic four legged beast.",
    "Marble Sphinx will answer three questions, painfully truthful.",
    "NPC adventuring party, devastated by poison gas trap.",
    "Huge containers hold gas for trap next door.",
    "Magical fisher&#39;s net holds water elemental captive.",
    "Sound of cracking whip whenever someone enters here.",
    "Coin golem protects altar to Mammon.",
    "Chain golems attend disciplinary wizard seeking looters/vandals",
    "Ocarina on corpse. Full of spiders. Summons drider. ",
    "Vampire gang, sharpening stakes, going to raid rivals",
    "Hordes writhe below, tortured. Random Inferno excerpt.",
    "Gem crusted scabbard, curses swords placed inside.",
    "Spinning jewel keeps dungeon level, slants when disturbed.",
    "Spyglass with amber glasses shows netherworld.",
    "North full of spikes. Six goblins impaled.",
    "Needle trap on locked doors.",
    "Two trolls grooming each other with bone combs.",
    "Map showing hidden rooms. Doesn&#39;t show traps.",
    "Terrible wailing from below through iron grates.",
    "A river of filth and refuse flows north-to-south.",
    "Filled waist high with feathers. Wizard researching Featherfall.",
    "Necrosurgeon rebuilds body for ogre client.",
    "Treasure room. Mimics forced to swallow treasure.",
    "Illusory bottomless pit, hides trapdoor to lower level.",
    "Express elevator in west wall, six levels down",
    "Four cryogenic chambers, three empty. One holds Starchild.",
    "South wall covered in rough map of dungeon level.",
    "Gilded ceiling reflects magic. Wizards take heed!",
    "Four casks full of salted eel.",
    "Collection of gems left behind by dying Xorn.",
    "Living statues trapped under rockfall. Ceiling unstable.",
    "Clerics of mutation attempting to convert dungeon people.",
    "Black crown, comprehend fungi save v madness.",
    "Down-sloping rough spiral. Bottom: throne, yellow robes.",
    "Board book detailing henchmen deaths. Piercers. Spike trap.",
    "Knights Of Purity cleansing dungeon room with bleach.",
    "Troll shaman flenses his arm to create magical glove.",
    "Mutated rat swarm attempts telepathic contact; easily overwhelming.",
    "Single boot of Elvenkind under heap of rubble.",
    "Children&#39;s toys litter the floor.",
    "Time inside moves 3d4 times faster than outside",
    "Mirror maze makes magic missile monstrous.",
    "Those who drink from dark pool fight shadows.",
    "Magical instrument plays welcome fanfare upon entering.",
    "Empty"
];

EMPTY_ROOMS = [
    "Aviary",
    "Bestiary",
    "Cage",
    "Cell",
    "Work Pit / Workshop",
    "Kennel",
    "Oubliette",
    "Padded Room",
    "Pen",
    "Prison",
    "Stockade",
    "Assemblage",
    "Antechamber",
    "Amphitheater",
    "Audience Hall",
    "Courtroom",
    "Great Hall",
    "Throne Room",
    "Zoo",
    "Statuary",
    "Torture Chamber",
    "Trophy Room",
    "Seraglio",
    "Arena",
    "Banquet",
    "Combat pit",
    "Pool / Water Room",
    "Den",
    "Game Room",
    "Office",
    "Gallery",
    "Meeting Chamber",
    "Mine",
    "Museum",
    "Music Room",
    "Pool",
    "Sauna",
    "Stable",
    "Bathroom",
    "Garage",
    "Treasury",
    "Bedroom",
    "Cistern Room",
    "Tannery",
    "Closet",
    "Dining Room",
    "Dressing Room",
    "Foyer (Entry Room)",
    "Hall",
    "Lair",
    "Larder / Pantry",
    "Lounge",
    "Map Room",
    "Privy",
    "Planning Room",
    "Reception Chamber",
    "Salon",
    "Servants Dorm",
    "Storage",
    "Waiting Room",
    "Wardrobe",
    "Well Room",
    "Vault",
    "Vestibule",
    "Armory",
    "Arsenal",
    "Barracks",
    "Guardroom",
    "Gymnasium",
    "Interrogation Room",
    "Mess Hall",
    "Training Room",
    "Chantry",
    "Chapel",
    "Crypt, Human",
    "Crypt, Animal",
    "Confessional",
    "Crematorium",
    "Embalming Chamber",
    "Meditation Chamber",
    "Monk Cell Mass",
    "Grave Robing Room",
    "Shrine",
    "Scriptorium",
    "Temple",
    "Forge",
    "Vestry",
    "Smokehouse",
    "Classroom",
    "Conjuring Room",
    "Divination Chamber",
    "Inscription Chamber",
    "Laboratory",
    "Library",
    "Morgue",
    "Observatory",
    "Study",
    "Solar",
    "Summoning Room",
    "Kitchen"
];
